#!/bin/bash
\cp /etc/haproxy/haproxy.cfg.masters /etc/haproxy/haproxy.cfg
systemctl restart haproxy
systemctl status haproxy

export KUBECONFIG=./dir_install/auth/kubeconfig

# echo '
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
  # name: registry-pv
# spec:
  # capacity:
    # storage: 100Gi
  # accessModes:
  # - ReadWriteMany
  # nfs:
    # path: /vmstore/registry
    # server: r720-a.home.io
  # persistentVolumeReclaimPolicy: Retain' | oc apply -f -

wait_time=240 # seconds
echo "Sleep for 4m before we patch the registry..."
echo ""
temp_cnt=${wait_time}
while [[ ${temp_cnt} -gt 0 ]];
do
    printf "\r%2d second(s) remaining." ${temp_cnt}
    sleep 1
    ((temp_cnt--))
done
echo ""

oc patch configs.imageregistry.operator.openshift.io cluster --type merge --patch '{"spec":{"storage":{"emptyDir":{}}}}'
# oc patch configs.imageregistry.operator.openshift.io cluster --type merge --patch '{"spec":{"storage":{"pvc":{"claim":""}}}}'
oc patch configs.imageregistry.operator.openshift.io cluster --type merge --patch '{"spec":{"managementState":"Managed"}}'

# htpasswd -c -B -b htpasswd.users jblaine redhat
# htpasswd -B -b htpasswd.users admin redhat
# htpasswd -B -b htpasswd.users user1 redhat
# cat htpasswd.users
# oc create secret generic htpass-secret --from-file=htpasswd=htpasswd.users -n openshift-config

echo '
---
apiVersion: v1
stringData:
  htpasswd: |-
    jblaine:$2y$05$senPDD414Jwxnuq2gaK8pO/2JVxCIYN6VWXpz6Tv1yjRq23NfATiO
    admin:$2y$05$IWGqLT7K/Y0L3qnTj48Q0O98qgbfkI6mgqsK3fOKTnMuNZFYmgnGG
    user1:$2y$05$I8f0EaUvWJk70zZE9t0zJ..kELKKkZXqpH8K1OONDeLfEhL.Md.g2
kind: Secret
metadata:
  name: htpass-secret
  namespace: openshift-config
type: Opaque' | oc apply -f - -n openshift-config

echo '
---
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: htpasswd
    mappingMethod: claim
    type: HTPasswd
    htpasswd:
      fileData:
        name: htpass-secret' | oc apply -f -

openshift-install wait-for install-complete --dir=/root/ocp/dir_install --log-level debug
oc adm policy add-cluster-role-to-user cluster-admin jblaine
oc patch configs.imageregistry.operator.openshift.io/cluster --patch '{"spec":{"defaultRoute":true}}' --type=merge
oc delete secrets kubeadmin -n kube-system
