#!/bin/bash
\rm -rf /root/ocp/dir_install /var/lib/matchbox/ignition/*

mkdir /root/ocp/dir_install

cp /root/ocp/install-config.yaml.bak /root/ocp/dir_install/install-config.yaml

openshift-install create manifests --dir=/root/ocp/dir_install/

\cp -avr /root/ocp/cluster-scheduler-02-config.yml /root/ocp/dir_install/manifests/
# \cp -avr /root/ocp/cluster-network-03-config.yml /root/ocp/dir_install/manifests/

# read -p "Press enter to continue"

openshift-install create ignition-configs --dir=/root/ocp/dir_install/

\rm /root/ocp/dir_install/.openshift_install.log /root/ocp/dir_install/.openshift_install_state.json

\cp /root/ocp/dir_install/master.ign /root/ocp/dir_install/worker.ign /root/ocp/dir_install/bootstrap.ign /var/lib/matchbox/ignition/

chown -R matchbox:matchbox /var/lib/matchbox/ignition/

\cp /etc/haproxy/haproxy.cfg.bootstrap /etc/haproxy/haproxy.cfg
systemctl restart haproxy
systemctl status haproxy
